name: Python Tests

on:
  push:
    branches:
      - '**'  # This will trigger on all branch pushes
  pull_request:
    branches:
      - main   # This will trigger on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']  # Using the same Python version as your local environment

    steps:
    - name: Check out repository
      uses: actions/checkout@v4  # Latest checkout action

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5  # Latest Python setup action
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest pytest-flask

    - name: Run tests
      run: |
        pytest -v
